### PR TITLE
Add nginx_up gauge

### PR DESCRIPTION
**Pull request by matsumana**
I want to check the nginx is up.
so add `nginx_up` like a [mysqld_exporter](https://github.com/prometheus/mysqld_exporter/blob/v0.9.0/mysqld_exporter.go#L153)

### CODE REVIEW

**Comment by matsumana** [comment]
Hello.
Would you please review this?

**Comment by discordianfish** [comment]
Sorry for not spotting this earlier. Right now the scrape should fail if nginx is unreachable. You can use the `up` mertric for monitoring this.

**Comment by matsumana** [comment]
Thank you for your reply.

> Right now the scrape should fail if nginx is unreachable. You can use the up mertric for monitoring this.

It seemed that no up metrics did not exist. so I sent this PR, is it already exists?

**Comment by discordianfish** [comment]
The `up` metric is provided by Prometheus itself. It's 0 if a configured target failed: https://prometheus.io/docs/concepts/jobs_instances/
Going to close this here for now. We can reopen if I missed something.

**Comment by seelensonne** [comment]
The `up` metric is `0` if the scrape itself fails. But if the scrape succeeds (i.e., Prometheus was able to talk to the exporter), then the `nginx_up` metric would tell if Nginx is up (`1`) or not (`0`).

**Comment by discordianfish** [comment]
Fair enough

**Comment by seelensonne** [comment]
Awseome! Thank you and @matsumana.

**Comment by matsumana** [comment]
Thank you, too.

**Pull request merged**
