### PR TITLE
use alpine for building the docker image

### PR DESCRIPTION
**Pull request by 0x46616c6b**
With this approach i could reduce the image size from 21.04 MB to 14.87 MB. Also a newer Golang Version is used.

### CODE REVIEW

**Comment by discordianfish** [comment]
I wanted to migrate this to https://github.com/prometheus/busybox - D you want to give it a shot with that base image?

**Comment by 0x46616c6b** [comment]
Sorry for the long delay. Is there any existing Exporter using busybox image?

**Comment by discordianfish** [comment]
@0x46616c6b Yes, all official exporters are using it. eg: https://github.com/prometheus/node_exporter/blob/master/Dockerfile#L1

**Comment by 0x46616c6b** [comment]
And how can I reproduce the Docker build locally?

**Comment by discordianfish** [comment]
@0x46616c6b The images are public, you can just use it and docker build will fetch the busybox base image. You can of course also build it yourself: https://github.com/prometheus/busybox

**Pull request closed without merging**
