### PR TITLE
Use locked dependencies; other improvements

### PR DESCRIPTION
**Pull request by wjkohnen**
Today I had to restart a service which failed to come up due to #23. Due to that occasion I took a closer look and implemented a few improvements that help to make build reproducible. The fix by EdSchouten #24 is included in this PR. 

Please consider to release with semantically versioned git tags and maybe publish containers using automated builds. 

See also #26.

### CODE REVIEW

**Comment by discordianfish** [comment]
Hi,

sorry for not seeing this earlier. This looks good, thanks! Can you rebase it and maybe update dep? 

Agree with everything you said and happy to merge further changes to add build configs. So far I just didn't get to it.

**Comment by wjkohnen** [comment]
Sure, no problem. I've created a new PR #33 for that, though. 

There should be no further changes needed in order to create an automated build on docker hub. Just create an automated build repository on hub.docker.com and point it to your GitHub repository.

**Comment by discordianfish** [comment]
Last time I tried it wasn't possible to sync git tags with image tags. Is that possible now? But I suppose I could just manually create a release for now.

**Comment by wjkohnen** [comment]
Uh yes, I remember. For "automatically" building tags, one has to create a build trigger for each tag. Which is not exactly automatic, but whatever. :)

**Pull request closed without merging**
